name       : brasero
version    : 3.12.3
release    : 12
source     :
    - https://download.gnome.org/sources/brasero/3.12/brasero-3.12.3.tar.xz : 87749eae33a141207d1b00be233b6d8045982ed3249ed4b98dae1f3a975fea15
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A disc burning application from GNOME
description: |
    A disc burning application from GNOME
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libburn-1)
    - pkgconfig(libcanberra)
    - pkgconfig(libisoburn-1)
    - pkgconfig(libisofs-1)
    - pkgconfig(libnotify)
    - pkgconfig(sm)
    - itstool
rundeps    :
    - dvd_rw-tools
    - cdrdao
    - cdrtools
setup      : |
    %configure --disable-static --enable-libburnia
build      : |
    %make
install    : |
    %make_install

