name       : brasero
version    : 3.12.1
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/brasero/3.12/brasero-3.12.1.tar.xz : 9a5eea53e57b66de3c7c8c2393ac21a58d5afa81c6cfb16b3c7f010a3d147127
license    : GPL
clang      : no
component  : multimedia.audio
summary    : A disc burning application for Gnome
description: |
    A disc burning application for Gnome
builddeps  :
    - itstool
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(sm)
    - pkgconfig(ice)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra)
    - pkgconfig(libburn-1)
    - pkgconfig(libisofs-1)
    - pkgconfig(libisoburn-1)
rundeps    :
    - dvd_rw-tools
setup      : |
    %configure --disable-static --enable-libburnia
build      : |
    %make
install    : |
    %make_install
    
