name       : brasero
version    : 3.12.2
release    : 9
source     :
    - https://ftp.gnome.org/pub/gnome/sources/brasero/3.12/brasero-3.12.2.tar.xz : 6822166f9d08efcf8d900cab6f563e87f49f0e078ca10595dcd908498ef12041
license    : GPL
clang      : no
component  : multimedia.audio
summary    : A disc burning application for Gnome
description: |
    A disc burning application for Gnome
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libburn-1)
    - pkgconfig(libcanberra)
    - pkgconfig(libisoburn-1)
    - pkgconfig(libisofs-1)
    - pkgconfig(libnotify)
    - pkgconfig(sm)
    - itstool
rundeps    :
    - dvd_rw-tools
    - cdrtools
setup      : |
    %configure --disable-static --enable-libburnia
build      : |
    %make
install    : |
    %make_install

